name: "01_S3Bucket"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/feature'
    uses: mrlkrish/Terraform_workflow_test/.github/workflows/aws_tf_plan.yml@feature
    with:
      path: S3Bucket
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: mrlkrish/Terraform_workflow_test/.github/workflows/aws_tf_appy.yml@feature
    with:
      path: S3Bucket
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    uses: mrlkrish/Terraform_workflow_test/.github/workflows/aws_tf_plan.yml
    with:
      path: S3Bucket
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Uat:
    needs: Plan_Uat
    uses: mrlkrish/Terraform_workflow_test/.github/workflows/aws_tf_appy.yml
    with:
      path: S3Bucket
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}